version: '3.2'

services:
  property-api:
    image: property-api
    build:
      context: property-api/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    links:
      - stub-dev-db
    environment:
      - UH_URL=Server=stub-dev-db;Database=uhsimulator;User Id='sa';Password='Rooty-Tooty';
  stub-dev-db:
    image: 775052747630.dkr.ecr.eu-west-2.amazonaws.com/hackney/universal-housing-simulator-loaded:9855e4d527519516e8138a026e900ae26b4be5f3
    ports:
      - 1433:1433

  property-api-test:
    image: property-api-test
    build:
      context: .
      dockerfile: property-api.Tests/Dockerfile
    environment:
      - TEST_UH_URL=Server=stub-test-db;Database=uhsimulator;User Id='sa';Password='Rooty-Tooty';
    links:
      - stub-test-db
  stub-test-db:
    image: 775052747630.dkr.ecr.eu-west-2.amazonaws.com/hackney/universal-housing-simulator:9855e4d527519516e8138a026e900ae26b4be5f3
    ports:
      - 1433:1433
