version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0
  aws-cli: circleci/aws-cli@0.1.9

commands:
  deploy-env:
    description: "Sets up aws cli and ecs-deploy to update a service with a target docker image"
    parameters:
      service-name:
        type: string
      image-tag:
        type: string
    steps:
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_ID_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_REGION
      - run:
          name: Install jq
          command: |
            sudo apt update
            sudo apt install jq
      - run:
          name: Install ecs deploy
          command: |
            sudo pip install ecs-deploy
      - run:
          name: Premote target image
          command: |
            ecs deploy \
            --access-key-id $AWS_ID_KEY \
            --secret-access-key $AWS_SECRET_KEY \
            --timeout 1800 \
            --region $AWS_REGION \
            --image << parameters.image-tag >> \
            $CLUSTER_NAME << parameters.service-name >>
          no_output_timeout: 30m

jobs:
  check:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_ID_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_REGION
      - aws-ecr/ecr-login
      - setup_remote_docker
      - run:
          name: build
          command: docker-compose build property-api-test
      - run:
          name: Run tests
          command: docker-compose up property-api-test

  deploy-to-development:
    docker:
      - image: circleci/python:3.7
    steps:
      - deploy-env:
          service-name: 'property-api-development'
          image-name: "$AWS_ECR_HOST/$AWS_ECR_PATH:$CIRCLE_SHA1"

  deploy-to-staging:
    docker:
      - image: circleci/python:3.7
    steps:
      - deploy-env:
          service-name: 'property-api-staging'
          image-tag: "$CIRCLE_SHA1"

  deploy-to-production:
    docker:
      - image: circleci/python:3.7
    steps:
      - deploy-env:
          service-name: 'property-api-production'
          image-name: "$AWS_ECR_HOST/$AWS_ECR_PATH:$CIRCLE_SHA1"

workflows:
  build-and-deploy:
      jobs:
#      - check
      - aws-ecr/build_and_push_image:
          name: build_and_push_image
          dockerfile: ./property-api/Dockerfile
          path: ./property-api
          account-url: AWS_ECR_HOST
          repo: $AWS_ECR_PATH
          aws-access-key-id: AWS_ID_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
#              only: master
              only: replace-ecs-deploy-tool

      - deploy-to-staging:
          requires:
#            - check
            - build_and_push_image
          filters:
            branches:
#              only: master
              only: replace-ecs-deploy-tool

#      - permit-staging-release:
#          type: approval
#          requires:
#            - deploy-to-development
#          filters:
#            branches:
#              only: master
#
#      - deploy-to-staging:
#          requires:
#            - permit-staging-release
#          filters:
#            branches:
#              only: master
#
#      - permit-production-release:
#          type: approval
#          requires:
#            - deploy-to-staging
#          filters:
#            branches:
#              only: master
#
#      - deploy-to-production:
#          requires:
#            - permit-production-release
#          filters:
#            branches:
#              only: master
